# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 repositories:
   - repository: coderepo
     endpoint: GitHubSK   
     name: gittestorganization1/CodeRepo
     type: github
     trigger:
      - '*'


trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


